### PR TITLE
examples: added two small examples with tutorials 1 and 2

### PR DESCRIPTION
**Pull request by edugrasa**
Added two more examples (very simple ones for tutorials 1 and 2 at the IRATI wiki)

### CODE REVIEW

**Comment by vmaffione** [comment]
Thanks, but why don't we add the renumbering demo? (or did we already?)

**Comment by edugrasa** [comment]
That's next on the list, but first I have to prepare a PR with an image containing the latest code (current image shipped with demonstrator is pristine-1.5). PR should come in a little while :)

**Comment by vmaffione** [comment]
Right, I was also building the image right now! let's see who is faster (I'm not kidding, maybe one of us runs into problems :) )

**Comment by edugrasa** [comment]
The build process worked, now trying the image with the renumbering demo..

**Comment by vmaffione** [comment]
yeah, also for me. but ok, let's use your image if you are doing the check.

**Comment by vmaffione** [comment]
I also updated the README sha info, so please pull first.

**Comment by edugrasa** [comment]
PR ready!

2017-02-20 17:03 GMT+01:00 Vincenzo Maffione <notifications@github.com>:

**Pull request merged**
