### PR TITLE
Add a couple of required features for experimentation

### PR DESCRIPTION
**Pull request by lbergesio**
1. Add `--include-dir` parameter to copy local directory to the created VMs
2. Allow modifying specific paremeters from policy sets  loaded from the default template

### CODE REVIEW

**Comment by vmaffione** [comment]
Ok, I added some commits on tops of this:
1) generalize --include-dir, replacing it with "--overlay"
2) fix ps_set(), it was not working to me while trying to specify a single parmeter as different from the default, it was giving exceptions

**Comment by vmaffione** [comment]
Can you please give a try to check that things are working as expected on your side?

**Comment by lbergesio** [comment]
It was working to me with no exceptions. Where did you observe them?

For example, this configuraton:

```
policy dcfabric rmt.pff multipath
policy dcfabric routing link-state routingAlgorithm=ECMPDijkstra
policy dcfabric enrollment-task default enrollTimeoutInMs=1
```

produced the following blocks:

```
"enrollmentTaskConfiguration": {
        "policySet": {
            "name": "default",
            "parameters": [
                {
                    "name": "enrollTimeoutInMs",
                    "value": "1" #default is 1000
                },
                {
                    "name": "watchdogPeriodInMs",
                    "value": "30000"
                },
                {
                    "name": "declaredDeadIntervalInMs",
                    "value": "120000"
                },
                {
                    "name": "neighborsEnrollerPeriodInMs",
                    "value": "0"
                },
                {
                    "name": "maxEnrollmentRetries",
                    "value": "0"
                }
            ],
            "version": "1"
        }
    },

    "routingConfiguration": {
        "policySet": {
            "name": "link-state",
            "parameters": [
                {
                    "name": "objectMaximumAge",
                    "value": "10000"
                },
                {
                    "name": "waitUntilReadCDAP",
                    "value": "5001"
                },
                {
                    "name": "waitUntilError",
                    "value": "5001"
                },
                {
                    "name": "waitUntilPDUFTComputation",
                    "value": "103"
                },
                {
                    "name": "waitUntilFSODBPropagation",
                    "value": "101"
                },
                {
                    "name": "waitUntilAgeIncrement",
                    "value": "997"
                },
                {
                    "name": "routingAlgorithm",
                    "value": "ECMPDijkstra"  #default is Dijkstra
                }
            ],
            "version": "1"
        }
    },
```

Anyway, this commit seems to work ok too.

**Comment by vmaffione** [comment]
I was observing exceptions in similar cases.. if it works now, never mind!

**Pull request merged**
